configuration:
  name: blanqa
  author: brmson

collection-reader:
  inherit: phases.collection.fixed-question
  qtext: "When did Watson compete in Jeopardy?"

pipeline:
  - inherit: ecd.phase
    name: answer-type-extractor
    options: |
      - inherit: phases.answertype.ephyra
    # TODO: Multiple answer types support
    # TODO: Revise the machine learning performed
    # TODO: Allow clarification in case of low confidence

  - inherit: ecd.phase
    name: keyterm-extractor
    options: |
      - inherit: phases.keyterm.ephyra
    # TODO: Keyphrases (bigrams)

  - inherit: ecd.phase
    name: passage-retrieval
    options: |
      - inherit: phases.passage.textfile
        file: "data/sample.txt"
    # TODO: Indri-indexed databases
    # TODO: Project Gutenberg
    # TODO: Wikipedia

  - inherit: ecd.phase
    name: information-extractor
    options: |
      - inherit: phases.ie.ne
    # TODO: Make this an internal pipeline - make UIMA types out of NamedEntity + Sentence
    # TODO: Ontologies support
    # TODO: Coreferences resolution
    # TODO: Non-trivial scoring (NE proximity scoring etc.)

  # TODO: Soft filter + supporting evidence retrieval

  - inherit: ecd.phase
    name: answer-generator
    options: |
      - inherit: phases.answer.basic
