configuration:
  name: blanqa
  author: brmson

collection-reader:
  inherit: phases.collection.fixed-question
  qtext: "What prize did Watson receive?"

pipeline:
  - inherit: ecd.phase
    name: answer-type-extractor
    options: |
      - inherit: phases.answertype.fixed
        atype: "NEnumber->NEmoney"

  - inherit: ecd.phase
    name: keyterm-extractor
    options: |
      - inherit: phases.keyterm.fixed
        keyterms: "prize|Watson|received"
        keyphrases: "Watson receive"

  - inherit: ecd.phase
    name: passage-retrieval
    options: |
      - inherit: phases.passage.textfile
        file: "data/sample.txt"
    # TODO: Indri-indexed databases
    # TODO: Project Gutenberg
    # TODO: Wikipedia

  - inherit: ecd.phase
    name: information-extractor
    options: |
      - inherit: phases.ie.ne
    # TODO: Ontologies support
    # TODO: Non-trivial scoring

  # TODO: Soft filter + supporting evidence retrieval

  - inherit: ecd.phase
    name: answer-generator
    options: |
      - inherit: phases.answer.basic

  - inherit: phases.util.AnnotationPrinter
